# Ruff configuration for modern Python linting

# Target Python 3.9+
target-version = "py39"

# Line length to match Black
line-length = 88

# Enable additional rules
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings  
    "F",   # Pyflakes
    "I",   # isort
    "N",   # pep8-naming
    "UP",  # pyupgrade
    "YTT", # flake8-2020
    "BLE", # flake8-blind-except
    "B",   # flake8-bugbear
    "A",   # flake8-builtins
    "COM", # flake8-commas
    "C4",  # flake8-comprehensions
    "DTZ", # flake8-datetimez
    "T10", # flake8-debugger
    "EM",  # flake8-errmsg
    "FA",  # flake8-future-annotations
    "ISC", # flake8-implicit-str-concat
    "ICN", # flake8-import-conventions
    "G",   # flake8-logging-format
    "INP", # flake8-no-pep420
    "PIE", # flake8-pie
    "T20", # flake8-print
    "PT",  # flake8-pytest-style
    "Q",   # flake8-quotes
    "RSE", # flake8-raise
    "RET", # flake8-return
    "SLF", # flake8-self
    "SIM", # flake8-simplify
    "TID", # flake8-tidy-imports
    "TCH", # flake8-type-checking
    "ARG", # flake8-unused-arguments
    "PTH", # flake8-use-pathlib
    "ERA", # eradicate
    "PL",  # Pylint
    "TRY", # tryceratops
    "FLY", # flynt
    "RUF", # Ruff-specific rules
]

# Ignore specific rules
ignore = [
    "E501",   # Line too long (handled by Black)
    "COM812", # Trailing comma missing (handled by Black)
    "ISC001", # Implicit string concatenation (conflicts with formatter)
    "PLR0913", # Too many arguments to function call
    "PLR0912", # Too many branches
    "PLR0915", # Too many statements
    "TRY003",  # Avoid specifying long messages outside exception class
]

# Exclude files and directories
exclude = [
    ".git",
    ".mypy_cache", 
    ".ruff_cache",
    ".tox",
    ".venv",
    "__pycache__",
    "build",
    "dist",
    "venv",
]

# Per-file ignores
[per-file-ignores]
"tests/**/*.py" = [
    "S101",   # Use of assert detected
    "ARG001", # Unused function argument
    "PLR2004", # Magic value used in comparison
]
"benchmarks/**/*.py" = [
    "T201",   # print() found
    "PLR2004", # Magic value used in comparison
]
"src/reflexion/cli.py" = [
    "T201",   # print() found
]

# Import settings
[isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

# Formatting settings  
[format]
quote-style = "double"
indent-style = "space"
# Configuration for ruff formatting