global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "reflexion_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Reflexion application metrics
  - job_name: 'reflexion'
    static_configs:
      - targets: ['reflexion:8000']
    scrape_interval: 10s
    metrics_path: '/metrics'
    
  # System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    
  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    
  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']