name: Bug Report
description: File a bug report to help us improve
title: "[BUG] "
labels: ["bug", "triage-needed"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛
        
        Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Please confirm the following before proceeding
      options:
        - label: I have searched for similar issues
          required: true
        - label: I have read the documentation
          required: true
        - label: I have checked the FAQ
          required: true

  - type: input
    attributes:
      label: Version
      description: What version of reflexion-agent-boilerplate are you using?
      placeholder: "e.g., 1.0.0"
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Python Version
      description: What version of Python are you using?
      options:
        - "3.9"
        - "3.10"
        - "3.11"
        - "3.12"
        - "Other (please specify in description)"
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - "Linux"
        - "macOS"
        - "Windows"
        - "Docker"
        - "Other (please specify in description)"
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Framework
      description: Which AI framework are you using (if applicable)?
      options:
        - "AutoGen"
        - "CrewAI"
        - "LangChain"
        - "Claude-Flow"
        - "None"
        - "Other (please specify in description)"

  - type: textarea
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Error Messages
      description: If applicable, add any error messages or stack traces
      placeholder: Paste error messages here...
      render: text

  - type: textarea
    attributes:
      label: Code Sample
      description: A minimal code sample that reproduces the issue
      placeholder: |
        ```python
        # Your code here
        ```
      render: python

  - type: textarea
    attributes:
      label: Configuration
      description: Relevant configuration (environment variables, config files, etc.)
      placeholder: |
        ```yaml
        # Your configuration here
        ```
      render: yaml

  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might help...

  - type: checkboxes
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have provided all the requested information
        - label: I have tested this with the latest version
        - label: I am willing to help test the fix