name: Security Vulnerability Report
description: Report a security vulnerability (do not use for sensitive issues)
title: "[SECURITY] "
labels: ["security", "triage-needed"]
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **WARNING**: Do not report sensitive security vulnerabilities here!
        
        For sensitive security issues, please email security@your-org.com instead.
        
        This form is only for non-sensitive security improvements and hardening suggestions.

  - type: checkboxes
    attributes:
      label: Security Checklist
      description: Please confirm this is appropriate for public reporting
      options:
        - label: This is NOT a sensitive security vulnerability
          required: true
        - label: I have read the security policy
          required: true
        - label: I have searched for similar issues
          required: true

  - type: dropdown
    attributes:
      label: Severity
      description: How would you rate the severity?
      options:
        - Low (security hardening suggestion)
        - Medium (potential security improvement)
      default: 0
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description
      description: Describe the security concern or improvement suggestion
      placeholder: Please provide a clear description of the security issue or improvement
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Step one
        2. Step two
        3. Step three
    validations:
      required: false

  - type: textarea
    attributes:
      label: Expected Behavior
      description: What should happen instead?
    validations:
      required: false

  - type: textarea
    attributes:
      label: Suggested Solution
      description: Do you have any suggestions for fixing this issue?
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context about the security concern
    validations:
      required: false